







#set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
#set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
#set_property PACKAGE_PIN W5 [get_ports clk]
#set_property PACKAGE_PIN P19 [get_ports h_sync]
#set_property PACKAGE_PIN R19 [get_ports v_sync]
#set_property PACKAGE_PIN G19 [get_ports {red[0]}]
#set_property PACKAGE_PIN H19 [get_ports {red[1]}]
#set_property PACKAGE_PIN J19 [get_ports {red[2]}]
#set_property PACKAGE_PIN N19 [get_ports {red[3]}]
#set_property PACKAGE_PIN J17 [get_ports {green[0]}]
#set_property PACKAGE_PIN H17 [get_ports {green[1]}]
#set_property PACKAGE_PIN G17 [get_ports {green[2]}]
#set_property PACKAGE_PIN D17 [get_ports {green[3]}]
#set_property PACKAGE_PIN N18 [get_ports {blue[0]}]
#set_property PACKAGE_PIN L18 [get_ports {blue[1]}]
#set_property PACKAGE_PIN K18 [get_ports {blue[2]}]
#set_property PACKAGE_PIN J18 [get_ports {blue[3]}]


set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
set_property PACKAGE_PIN P19 [get_ports h_sync]
set_property PACKAGE_PIN R19 [get_ports v_sync]


set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]
set_property PACKAGE_PIN J17 [get_ports {green[0]}]
set_property PACKAGE_PIN H17 [get_ports {green[1]}]
set_property PACKAGE_PIN G17 [get_ports {green[2]}]
set_property PACKAGE_PIN D17 [get_ports {green[3]}]
set_property PACKAGE_PIN G19 [get_ports {red[0]}]
set_property PACKAGE_PIN H19 [get_ports {red[1]}]
set_property PACKAGE_PIN J19 [get_ports {red[2]}]
set_property PACKAGE_PIN N19 [get_ports {red[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_signal[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_signal[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_signal[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_signal[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_signal[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_signal[1]}]
set_property PACKAGE_PIN J3 [get_ports {ir_signal[5]}]
set_property PACKAGE_PIN L3 [get_ports {ir_signal[4]}]
set_property PACKAGE_PIN M2 [get_ports {ir_signal[3]}]
set_property PACKAGE_PIN N2 [get_ports {ir_signal[2]}]
set_property PACKAGE_PIN K3 [get_ports {ir_signal[1]}]
set_property PACKAGE_PIN M3 [get_ports {ir_signal[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports switch]
set_property PACKAGE_PIN T1 [get_ports switch]
